In [1]:
import numpy as np

# Complex Numbers

In [2]:
z = 5+4j

In [3]:
print(f'The Real part of z: {np.real(z)}')
print(f'The Imaginary part of z: {np.imag(z)}')

The Real part of z: 5.0
The Imaginary part of z: 4.0


In [13]:
w = 3-2j

In [14]:
z+w

(8+2j)

In [15]:
## complex conjugate

print(f'The Complex number w: {w}')
print(f'The Complex conjugate of w: {np.conj(w)}')

The Complex number w: (3-2j)
The Complex conjugate of w: (3+2j)


In [16]:
## Normal and Absolute values

print(f'The Complex number z: {z}')
print(f'The absolute value of z: {np.abs(z)}')

The Complex number z: (5+4j)
The absolute value of z: 6.4031242374328485


In [17]:
print(f'The Complex number w: {w}')
print(f'The absolute value of w: {np.abs(w)}')

The Complex number w: (3-2j)
The absolute value of w: 3.605551275463989


# Bra-Ket Notation

In [18]:
row_vec = np.array([10, 5+2j, 3.2])

row_vec

array([10. +0.j,  5. +2.j,  3.2+0.j])

In [19]:
col_vec = np.array([[1,2],[3,3-2j]])

col_vec

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 3.-2.j]])

In quantum space, row vectors are called '**Bra-vectors**' and column vectors are called '**Ket-vectors**'

The notations are:

- ROW VECTOR: <A| = (v1,v2,...,vn)
- COL VECTOR: B|> = (v1)
                  (v2)
                  (..)
                  (vn)
                  
                  
If you are having a ket-vector, then to get the corresponding bra-vector, you would need to take the complex conjugate of the ket-vector.

In [23]:
## doing inner products between Bra and ket vectors

A = np.array([[4],[3-2j],[2],[1]]) ## a ket vector of 4x1 dim

In [24]:
B = np.array([1,5,-4j,2j]) ## a bra-vector of 1x4 dim

In [25]:
np.dot(B,A)

array([19.-16.j])

In [29]:
### Matrics
## In quantum world, its called operators

M = np.array([[2+1j, -0.1+5j],[-3, 4_8j]])

print(M)

[[ 2.  +1.j -0.1 +5.j]
 [-3.  +0.j  0. +48.j]]


In [30]:
M = np.matrix([[2+1j, -0.1+5j],[-3, 4_8j]])

print(M)

[[ 2.  +1.j -0.1 +5.j]
 [-3.  +0.j  0. +48.j]]


[Hermitian conjugate](https://en.wikipedia.org/wiki/Conjugate_transpose) is the conjugate transpose of a matrix.

In [34]:
M.H  # the hermitian conjugate of the matrix

matrix([[ 2.  -1.j, -3.  -0.j],
        [-0.1 -5.j,  0. -48.j]])

# Tensor product of matrices

In [35]:
np.kron(M,M) ## matrix product

matrix([[ 3.000e+00  +4.j , -5.200e+00  +9.9j, -5.200e+00  +9.9j,
         -2.499e+01  -1.j ],
        [-6.000e+00  -3.j , -4.800e+01 +96.j ,  3.000e-01 -15.j ,
         -2.400e+02  -4.8j],
        [-6.000e+00  -3.j ,  3.000e-01 -15.j , -4.800e+01 +96.j ,
         -2.400e+02  -4.8j],
        [ 9.000e+00  -0.j , -0.000e+00-144.j , -0.000e+00-144.j ,
         -2.304e+03  +0.j ]])